In [44]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [47]:
print(arr.dtype)

int64


In [52]:
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [54]:
print(arr1[0][2])

3


In [64]:
import numpy as np
calculator = np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])
print(calculator)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [65]:
print(calculator.transpose())

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]


In [66]:
print(calculator.shape)

(3, 4)


In [68]:
arr1 = calculator.reshape(2,6)
print(arr1)

[[ 1  2  3 10  4  5]
 [ 6 11  7  8  9 12]]


In [76]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[7,8,9],[10,11,12]])
farr = np.concatenate((arr2,arr3),axis=0)
print(farr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [81]:
x = np.where(arr3 == 7)
print(x)

(array([0]), array([0]))


In [86]:
import numpy as np
arr = np.array([1,2,3,4,5,2,4,3,4,2,2,3,5])
x = np.where(arr%2 == 0)
print(x[0])

[ 1  3  5  6  8  9 10]


In [88]:
import numpy as np
arr = np.array([3,2,6,7,4,9,8,1,5])
print(np.sort(arr)[::-1])

[9 8 7 6 5 4 3 2 1]


In [90]:
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

print(arr1[::-1,:])
print(arr1[:,::-1])

[[1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]
 [1 2 3 4]]
[[4 3 2 1]
 [8 7 6 5]]
